name: loren_frank_data_processing
channels:
- conda-forge
- defaults
dependencies:
- python
- numpy
- pandas
- xarray
- dask
- scipy
- netcdf4
- ffmpeg
- matplotlib
- networkx
- pytest
- pytest-cov
- coveralls
- setuptools
- jupyter
- jupyterlab
- nb_conda
- setuptools
- pip
- pip:
  - nb_black
