name: loren_frank_data_processing
channels:
- conda-forge
- defaults
dependencies:
- "python >= 3.5"
- "numpy >= 1.11"
- "pandas >= 0.18.0"
- xarray
- scipy
- "pytest >= 2.7.1"
- pytest-cov
- coveralls
- setuptools
- jupyter
- numpydoc
- sphinx
- pip:
  - twine
