name: loren_frank_data_processing
channels:
- conda-forge
- defaults
dependencies:
- "python >= 3.4"
- "numpy >= 1.11"
- "pandas >= 0.18.0"
- xarray
- dask
- scipy
- netcdf4
- "networkx >= 2.0"
- "pytest >= 2.7.1"
- pytest-cov
- coveralls
- setuptools
- jupyter
- numpydoc
- sphinx
